// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesMovie.Data;

#nullable disable

namespace RazorPagesMovie.Migrations
{
    [DbContext(typeof(RazorPagesMovieContext))]
    partial class RazorPagesMovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("RazorPagesMovie.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Actor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1942, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laurie Lesch"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1968, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rhett Ullrich"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1991, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ivy Schoen"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1981, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mario Renner"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1944, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nedra Buckridge"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1967, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oda Gleichner"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1945, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laney Stroman"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1989, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Clotilde Douglas"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1950, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mose Goldner"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1974, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ralph Littel"
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1949, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lilla Schmeler"
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(1953, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marisa Paucek"
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1996, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Terence Bauch"
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1952, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lera Dicki"
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(1958, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Natasha Wunsch"
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(1974, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Margaret Breitenberg"
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(2003, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Raoul Kshlerin"
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(1955, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Braxton Wolf"
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(1961, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sheila Jacobi"
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(1981, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Doris Boyer"
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(1957, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Donnie Nitzsche"
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateTime(2000, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Deshaun Beier"
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateTime(1968, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jeanie Bergnaum"
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateTime(1954, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rudy Stark"
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateTime(1984, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kathleen Wuckert"
                        },
                        new
                        {
                            Id = 26,
                            DateOfBirth = new DateTime(1954, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sofia Kling"
                        },
                        new
                        {
                            Id = 27,
                            DateOfBirth = new DateTime(1950, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jasen Beier"
                        },
                        new
                        {
                            Id = 28,
                            DateOfBirth = new DateTime(1943, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lou Zieme"
                        },
                        new
                        {
                            Id = 29,
                            DateOfBirth = new DateTime(1993, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Keenan Kulas"
                        },
                        new
                        {
                            Id = 30,
                            DateOfBirth = new DateTime(1958, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tabitha Schinner"
                        },
                        new
                        {
                            Id = 31,
                            DateOfBirth = new DateTime(2001, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Shanelle Nolan"
                        },
                        new
                        {
                            Id = 32,
                            DateOfBirth = new DateTime(1975, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Daryl Heaney"
                        },
                        new
                        {
                            Id = 33,
                            DateOfBirth = new DateTime(1999, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tiana Kuhlman"
                        },
                        new
                        {
                            Id = 34,
                            DateOfBirth = new DateTime(1942, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Felipe Denesik"
                        },
                        new
                        {
                            Id = 35,
                            DateOfBirth = new DateTime(1980, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "August Williamson"
                        },
                        new
                        {
                            Id = 36,
                            DateOfBirth = new DateTime(2004, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nia Mayert"
                        },
                        new
                        {
                            Id = 37,
                            DateOfBirth = new DateTime(2001, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Keely Zboncak"
                        },
                        new
                        {
                            Id = 38,
                            DateOfBirth = new DateTime(1942, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bertha Schinner"
                        },
                        new
                        {
                            Id = 39,
                            DateOfBirth = new DateTime(1981, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Janelle Nicolas"
                        },
                        new
                        {
                            Id = 40,
                            DateOfBirth = new DateTime(1976, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Concepcion Predovic"
                        },
                        new
                        {
                            Id = 41,
                            DateOfBirth = new DateTime(1957, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bertram Mayer"
                        },
                        new
                        {
                            Id = 42,
                            DateOfBirth = new DateTime(1953, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bud Wolf"
                        },
                        new
                        {
                            Id = 43,
                            DateOfBirth = new DateTime(1981, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dylan Haley"
                        },
                        new
                        {
                            Id = 44,
                            DateOfBirth = new DateTime(2002, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Braxton Wisozk"
                        },
                        new
                        {
                            Id = 45,
                            DateOfBirth = new DateTime(1996, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eliezer Cassin"
                        },
                        new
                        {
                            Id = 46,
                            DateOfBirth = new DateTime(1942, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Brady Little"
                        },
                        new
                        {
                            Id = 47,
                            DateOfBirth = new DateTime(1999, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hipolito Schoen"
                        },
                        new
                        {
                            Id = 48,
                            DateOfBirth = new DateTime(1992, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Retha Heller"
                        },
                        new
                        {
                            Id = 49,
                            DateOfBirth = new DateTime(1994, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Everardo Runte"
                        },
                        new
                        {
                            Id = 50,
                            DateOfBirth = new DateTime(1985, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tabitha Runolfsson"
                        },
                        new
                        {
                            Id = 51,
                            DateOfBirth = new DateTime(1991, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stevie Reichert"
                        },
                        new
                        {
                            Id = 52,
                            DateOfBirth = new DateTime(1979, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Felix Fisher"
                        },
                        new
                        {
                            Id = 53,
                            DateOfBirth = new DateTime(2003, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Olen White"
                        },
                        new
                        {
                            Id = 54,
                            DateOfBirth = new DateTime(1957, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Helen Kozey"
                        },
                        new
                        {
                            Id = 55,
                            DateOfBirth = new DateTime(1941, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Florine Keeling"
                        },
                        new
                        {
                            Id = 56,
                            DateOfBirth = new DateTime(1983, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wilford Schulist"
                        },
                        new
                        {
                            Id = 57,
                            DateOfBirth = new DateTime(1945, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Carolina Heathcote"
                        },
                        new
                        {
                            Id = 58,
                            DateOfBirth = new DateTime(1997, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lelia Rutherford"
                        },
                        new
                        {
                            Id = 59,
                            DateOfBirth = new DateTime(1954, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Madisen Green"
                        },
                        new
                        {
                            Id = 60,
                            DateOfBirth = new DateTime(1953, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jamaal Schmidt"
                        },
                        new
                        {
                            Id = 61,
                            DateOfBirth = new DateTime(1975, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Francisco Hilpert"
                        },
                        new
                        {
                            Id = 62,
                            DateOfBirth = new DateTime(1956, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Torrance Fahey"
                        },
                        new
                        {
                            Id = 63,
                            DateOfBirth = new DateTime(1997, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chadd West"
                        },
                        new
                        {
                            Id = 64,
                            DateOfBirth = new DateTime(1978, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dixie Hermann"
                        },
                        new
                        {
                            Id = 65,
                            DateOfBirth = new DateTime(1961, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Anabelle Altenwerth"
                        },
                        new
                        {
                            Id = 66,
                            DateOfBirth = new DateTime(1999, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Luz Konopelski"
                        },
                        new
                        {
                            Id = 67,
                            DateOfBirth = new DateTime(2002, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Otilia Hickle"
                        },
                        new
                        {
                            Id = 68,
                            DateOfBirth = new DateTime(1967, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chandler Rohan"
                        },
                        new
                        {
                            Id = 69,
                            DateOfBirth = new DateTime(2001, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lesley Gulgowski"
                        },
                        new
                        {
                            Id = 70,
                            DateOfBirth = new DateTime(2001, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stevie Predovic"
                        },
                        new
                        {
                            Id = 71,
                            DateOfBirth = new DateTime(1949, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Georgiana Hackett"
                        },
                        new
                        {
                            Id = 72,
                            DateOfBirth = new DateTime(1946, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ora Beer"
                        },
                        new
                        {
                            Id = 73,
                            DateOfBirth = new DateTime(1953, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mike Kautzer"
                        },
                        new
                        {
                            Id = 74,
                            DateOfBirth = new DateTime(1996, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Onie Schneider"
                        },
                        new
                        {
                            Id = 75,
                            DateOfBirth = new DateTime(2004, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ozella Tremblay"
                        },
                        new
                        {
                            Id = 76,
                            DateOfBirth = new DateTime(1989, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jerrold Lowe"
                        },
                        new
                        {
                            Id = 77,
                            DateOfBirth = new DateTime(1993, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kattie Altenwerth"
                        },
                        new
                        {
                            Id = 78,
                            DateOfBirth = new DateTime(1968, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Elody Parker"
                        },
                        new
                        {
                            Id = 79,
                            DateOfBirth = new DateTime(1980, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dennis Dickens"
                        },
                        new
                        {
                            Id = 80,
                            DateOfBirth = new DateTime(2000, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Brady Hammes"
                        },
                        new
                        {
                            Id = 81,
                            DateOfBirth = new DateTime(1956, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eli Glover"
                        },
                        new
                        {
                            Id = 82,
                            DateOfBirth = new DateTime(1943, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Travon Torp"
                        },
                        new
                        {
                            Id = 83,
                            DateOfBirth = new DateTime(2001, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Isabella Goyette"
                        },
                        new
                        {
                            Id = 84,
                            DateOfBirth = new DateTime(1942, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Darron Waters"
                        },
                        new
                        {
                            Id = 85,
                            DateOfBirth = new DateTime(1976, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Micheal Adams"
                        },
                        new
                        {
                            Id = 86,
                            DateOfBirth = new DateTime(1995, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ashley Hudson"
                        },
                        new
                        {
                            Id = 87,
                            DateOfBirth = new DateTime(1988, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Holden Buckridge"
                        },
                        new
                        {
                            Id = 88,
                            DateOfBirth = new DateTime(1984, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cielo Heller"
                        },
                        new
                        {
                            Id = 89,
                            DateOfBirth = new DateTime(1980, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Branson Blanda"
                        },
                        new
                        {
                            Id = 90,
                            DateOfBirth = new DateTime(1996, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Merritt Ledner"
                        },
                        new
                        {
                            Id = 91,
                            DateOfBirth = new DateTime(1946, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jaunita Medhurst"
                        },
                        new
                        {
                            Id = 92,
                            DateOfBirth = new DateTime(1974, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dortha Kreiger"
                        },
                        new
                        {
                            Id = 93,
                            DateOfBirth = new DateTime(1940, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lew Stark"
                        },
                        new
                        {
                            Id = 94,
                            DateOfBirth = new DateTime(1957, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tyreek Beatty"
                        },
                        new
                        {
                            Id = 95,
                            DateOfBirth = new DateTime(1945, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ramiro Hamill"
                        },
                        new
                        {
                            Id = 96,
                            DateOfBirth = new DateTime(1983, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Otho McLaughlin"
                        },
                        new
                        {
                            Id = 97,
                            DateOfBirth = new DateTime(1991, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Serena Cummerata"
                        },
                        new
                        {
                            Id = 98,
                            DateOfBirth = new DateTime(1953, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ocie Pouros"
                        },
                        new
                        {
                            Id = 99,
                            DateOfBirth = new DateTime(1999, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chester Brown"
                        },
                        new
                        {
                            Id = 100,
                            DateOfBirth = new DateTime(1992, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kelvin Schoen"
                        });
                });

            modelBuilder.Entity("RazorPagesMovie.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BoxOfficeRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cast")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImdbRating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseCountry")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.MovieActor", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActor");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.MovieActor", b =>
                {
                    b.HasOne("RazorPagesMovie.Models.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazorPagesMovie.Models.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.Movie", b =>
                {
                    b.Navigation("MovieActors");
                });
#pragma warning restore 612, 618
        }
    }
}
